export const mossyDefaultScaleValues = {
  "dimension-x0_5": "2px",
  "dimension-x1": "4px",
  "dimension-x1_5": "6px",
  "dimension-x2": "8px",
  "dimension-x2_5": "10px",
  "dimension-x3": "12px",
  "dimension-x3_5": "14px",
  "dimension-x4": "16px",
  "dimension-x4_5": "18px",
  "dimension-x5": "20px",
  "dimension-x6": "24px",
  "dimension-x7": "28px",
  "dimension-x8": "32px",
  "dimension-x9": "36px",
  "dimension-x10": "40px",
  "dimension-x12": "48px",
  "dimension-x13": "52px",
  "dimension-x14": "56px",
  "dimension-x16": "64px",
  "dimension-spacing-x-between-chips": "var(--mossy-dimension-x2)",
  "dimension-spacing-x-global-gutter": "var(--mossy-dimension-x4)",
  "dimension-spacing-y-component-default": "var(--mossy-dimension-x3)",
  "dimension-spacing-y-nav-to-title": "var(--mossy-dimension-x5)",
  "dimension-spacing-y-screen-bottom": "var(--mossy-dimension-x14)",
  "dimension-spacing-y-between-text": "var(--mossy-dimension-x1_5)",
  "duration-d1": "50ms",
  "duration-d2": ".1s",
  "duration-d3": ".15s",
  "duration-d4": ".2s",
  "duration-d5": ".25s",
  "duration-d6": ".3s",
  "duration-color-transition": "var(--mossy-duration-d3)",
  "duration-pressed-scale": "var(--mossy-duration-d3)",
  "font-size-t1": "clamp(calc(var(--mossy-font-size-t1-static) * var(--mossy-font-size-limit-min, .8)), calc(.6875rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t1-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t2": "clamp(calc(var(--mossy-font-size-t2-static) * var(--mossy-font-size-limit-min, .8)), calc(.75rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t2-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t3": "clamp(calc(var(--mossy-font-size-t3-static) * var(--mossy-font-size-limit-min, .8)), calc(.8125rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t3-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t4": "clamp(calc(var(--mossy-font-size-t4-static) * var(--mossy-font-size-limit-min, .8)), calc(.875rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t4-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t5": "clamp(calc(var(--mossy-font-size-t5-static) * var(--mossy-font-size-limit-min, .8)), calc(1rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t5-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t6": "clamp(calc(var(--mossy-font-size-t6-static) * var(--mossy-font-size-limit-min, .8)), calc(1.125rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t6-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t7": "clamp(calc(var(--mossy-font-size-t7-static) * var(--mossy-font-size-limit-min, .8)), calc(1.25rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t7-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t8": "clamp(calc(var(--mossy-font-size-t8-static) * var(--mossy-font-size-limit-min, .8)), calc(1.375rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t8-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t9": "clamp(calc(var(--mossy-font-size-t9-static) * var(--mossy-font-size-limit-min, .8)), calc(1.5rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t9-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t10": "clamp(calc(var(--mossy-font-size-t10-static) * var(--mossy-font-size-limit-min, .8)), calc(1.625rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-font-size-t10-static) * var(--mossy-font-size-limit-max, 1.5)))",
  "font-size-t1-static": "11px",
  "font-size-t2-static": "12px",
  "font-size-t3-static": "13px",
  "font-size-t4-static": "14px",
  "font-size-t5-static": "16px",
  "font-size-t6-static": "18px",
  "font-size-t7-static": "20px",
  "font-size-t8-static": "22px",
  "font-size-t9-static": "24px",
  "font-size-t10-static": "26px",
  "font-weight-regular": "400",
  "font-weight-medium": "500",
  "font-weight-bold": "700",
  "line-height-t1": "clamp(calc(var(--mossy-line-height-t1-static) * var(--mossy-line-height-limit-min, .8)), calc(.9375rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t1-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t2": "clamp(calc(var(--mossy-line-height-t2-static) * var(--mossy-line-height-limit-min, .8)), calc(1rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t2-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t3": "clamp(calc(var(--mossy-line-height-t3-static) * var(--mossy-line-height-limit-min, .8)), calc(1.125rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t3-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t4": "clamp(calc(var(--mossy-line-height-t4-static) * var(--mossy-line-height-limit-min, .8)), calc(1.1875rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t4-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t5": "clamp(calc(var(--mossy-line-height-t5-static) * var(--mossy-line-height-limit-min, .8)), calc(1.375rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t5-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t6": "clamp(calc(var(--mossy-line-height-t6-static) * var(--mossy-line-height-limit-min, .8)), calc(1.5rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t6-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t7": "clamp(calc(var(--mossy-line-height-t7-static) * var(--mossy-line-height-limit-min, .8)), calc(1.6875rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t7-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t8": "clamp(calc(var(--mossy-line-height-t8-static) * var(--mossy-line-height-limit-min, .8)), calc(1.875rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t8-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t9": "clamp(calc(var(--mossy-line-height-t9-static) * var(--mossy-line-height-limit-min, .8)), calc(2rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t9-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t10": "clamp(calc(var(--mossy-line-height-t10-static) * var(--mossy-line-height-limit-min, .8)), calc(2.1875rem * var(--mossy-font-size-multiplier, 1)), calc(var(--mossy-line-height-t10-static) * var(--mossy-line-height-limit-max, 1.5)))",
  "line-height-t1-static": "15px",
  "line-height-t2-static": "16px",
  "line-height-t3-static": "18px",
  "line-height-t4-static": "19px",
  "line-height-t5-static": "22px",
  "line-height-t6-static": "24px",
  "line-height-t7-static": "27px",
  "line-height-t8-static": "30px",
  "line-height-t9-static": "32px",
  "line-height-t10-static": "35px",
  "radius-r0_5": "2px",
  "radius-r1": "4px",
  "radius-r1_5": "6px",
  "radius-r2": "8px",
  "radius-r2_5": "10px",
  "radius-r3": "12px",
  "radius-r3_5": "14px",
  "radius-r4": "16px",
  "radius-r5": "20px",
  "radius-r6": "24px",
  "radius-full": "9999px",
  "timing-function-linear": "cubic-bezier(0, 0, 1, 1)",
  "timing-function-easing": "cubic-bezier(.35, 0, .35, 1)",
  "timing-function-enter": "cubic-bezier(0, 0, .15, 1)",
  "timing-function-exit": "cubic-bezier(.35, 0, 1, 1)",
  "timing-function-enter-expressive": "cubic-bezier(.03, .4, .1, 1)",
  "timing-function-exit-expressive": "cubic-bezier(.35, 0, .95, .55)",
  "timing-function-pressed-scale": "cubic-bezier(0, 0, .15, 1)"
} as const;

export const mossyDefaultLightValues = {
  "color-palette-gray-00": "#fff",
  "color-palette-gray-100": "#f7f8f9",
  "color-palette-gray-200": "#f3f4f5",
  "color-palette-gray-300": "#eeeff1",
  "color-palette-gray-400": "#dcdee3",
  "color-palette-gray-500": "#d1d3d8",
  "color-palette-gray-600": "#b0b3ba",
  "color-palette-gray-700": "#868b94",
  "color-palette-gray-800": "#555d6d",
  "color-palette-gray-900": "#2a3038",
  "color-palette-gray-1000": "#1a1c20",
  "color-palette-mossy-100": "#f1f7f3",
  "color-palette-mossy-200": "#e2efe6",
  "color-palette-mossy-300": "#c9e1d0",
  "color-palette-mossy-400": "#a9cbaf",
  "color-palette-mossy-500": "#7fae88",
  "color-palette-mossy-600": "#4a7c59",
  "color-palette-mossy-700": "#3f6b4d",
  "color-palette-mossy-800": "#34583f",
  "color-palette-mossy-900": "#2a4633",
  "color-palette-mossy-1000": "#17281d",
  "color-palette-blue-100": "#eff6ff",
  "color-palette-blue-200": "#e2edfc",
  "color-palette-blue-300": "#cbdffa",
  "color-palette-blue-400": "#aacefd",
  "color-palette-blue-500": "#85b8fd",
  "color-palette-blue-600": "#5e98fe",
  "color-palette-blue-700": "#217cf9",
  "color-palette-blue-800": "#135fcd",
  "color-palette-blue-900": "#0b4596",
  "color-palette-blue-1000": "#032451",
  "color-palette-red-100": "#fdf0f0",
  "color-palette-red-200": "#fde7e7",
  "color-palette-red-300": "#fed4d2",
  "color-palette-red-400": "#feb7b3",
  "color-palette-red-500": "#fe928d",
  "color-palette-red-600": "#fc6a66",
  "color-palette-red-700": "#fa342c",
  "color-palette-red-800": "#ca1d13",
  "color-palette-red-900": "#921708",
  "color-palette-red-1000": "#4a1209",
  "color-palette-green-100": "#edfaf6",
  "color-palette-green-200": "#d9f6e9",
  "color-palette-green-300": "#b9e9d2",
  "color-palette-green-400": "#7ddcb3",
  "color-palette-green-500": "#42c593",
  "color-palette-green-600": "#10ab7d",
  "color-palette-green-700": "#079171",
  "color-palette-green-800": "#00745f",
  "color-palette-green-900": "#075445",
  "color-palette-green-1000": "#0a2b24",
  "color-palette-yellow-100": "#fff7de",
  "color-palette-yellow-200": "#fdefb9",
  "color-palette-yellow-300": "#fbdc65",
  "color-palette-yellow-400": "#e9c647",
  "color-palette-yellow-500": "#d4ab28",
  "color-palette-yellow-600": "#c49725",
  "color-palette-yellow-700": "#9b7821",
  "color-palette-yellow-800": "#755b22",
  "color-palette-yellow-900": "#4f3e1f",
  "color-palette-yellow-1000": "#2c2512",
  "color-palette-purple-100": "#f5f3fe",
  "color-palette-purple-200": "#efeafe",
  "color-palette-purple-300": "#e1d8ff",
  "color-palette-purple-400": "#d0c0ff",
  "color-palette-purple-500": "#b8a1ff",
  "color-palette-purple-600": "#9f84fb",
  "color-palette-purple-700": "#8969ea",
  "color-palette-purple-800": "#6d50cb",
  "color-palette-purple-900": "#50379b",
  "color-palette-purple-1000": "#29175d",
  "color-palette-static-black": "#000",
  "color-palette-static-black-alpha-100": "#00000007",
  "color-palette-static-black-alpha-200": "#0000000c",
  "color-palette-static-black-alpha-300": "#00000010",
  "color-palette-static-black-alpha-400": "#00000021",
  "color-palette-static-black-alpha-500": "#0000002c",
  "color-palette-static-black-alpha-600": "#0000004c",
  "color-palette-static-black-alpha-700": "#00000074",
  "color-palette-static-black-alpha-800": "#000000a2",
  "color-palette-static-black-alpha-900": "#000000d0",
  "color-palette-static-black-alpha-1000": "#000000e3",
  "color-palette-static-white": "#fff",
  "color-palette-static-white-alpha-50": "#ffffff0d",
  "color-palette-static-white-alpha-100": "#ffffff17",
  "color-palette-static-white-alpha-200": "#ffffff20",
  "color-palette-static-white-alpha-300": "#ffffff2e",
  "color-palette-static-white-alpha-400": "#ffffff3d",
  "color-palette-static-white-alpha-500": "#ffffff60",
  "color-palette-static-white-alpha-600": "#ffffff8b",
  "color-palette-static-white-alpha-700": "#ffffffb3",
  "color-palette-static-white-alpha-800": "#ffffffde",
  "color-palette-static-white-alpha-900": "#ffffffea",
  "color-palette-static-white-alpha-1000": "#fffffff4",
  "color-fg-brand": "var(--mossy-color-palette-mossy-600)",
  "color-fg-brand-contrast": "var(--mossy-color-palette-mossy-700)",
  "color-fg-critical": "var(--mossy-color-palette-red-700)",
  "color-fg-critical-contrast": "var(--mossy-color-palette-red-900)",
  "color-fg-disabled": "var(--mossy-color-palette-gray-500)",
  "color-fg-informative": "var(--mossy-color-palette-blue-700)",
  "color-fg-informative-contrast": "var(--mossy-color-palette-blue-900)",
  "color-fg-neutral": "var(--mossy-color-palette-gray-1000)",
  "color-fg-neutral-inverted": "var(--mossy-color-palette-gray-00)",
  "color-fg-neutral-muted": "var(--mossy-color-palette-gray-800)",
  "color-fg-neutral-subtle": "var(--mossy-color-palette-gray-700)",
  "color-fg-placeholder": "var(--mossy-color-palette-gray-600)",
  "color-fg-positive": "var(--mossy-color-palette-green-700)",
  "color-fg-positive-contrast": "var(--mossy-color-palette-green-900)",
  "color-fg-warning": "var(--mossy-color-palette-yellow-700)",
  "color-fg-warning-contrast": "var(--mossy-color-palette-yellow-900)",
  "color-bg-brand-solid": "var(--mossy-color-palette-mossy-600)",
  "color-bg-brand-solid-pressed": "var(--mossy-color-palette-mossy-700)",
  "color-bg-brand-weak": "var(--mossy-color-palette-mossy-100)",
  "color-bg-brand-weak-pressed": "var(--mossy-color-palette-mossy-200)",
  "color-bg-critical-solid": "var(--mossy-color-palette-red-700)",
  "color-bg-critical-solid-pressed": "var(--mossy-color-palette-red-800)",
  "color-bg-critical-weak": "var(--mossy-color-palette-red-100)",
  "color-bg-critical-weak-pressed": "var(--mossy-color-palette-red-200)",
  "color-bg-disabled": "var(--mossy-color-palette-gray-200)",
  "color-bg-informative-solid": "var(--mossy-color-palette-blue-700)",
  "color-bg-informative-solid-pressed": "var(--mossy-color-palette-blue-800)",
  "color-bg-informative-weak": "var(--mossy-color-palette-blue-100)",
  "color-bg-informative-weak-pressed": "var(--mossy-color-palette-blue-200)",
  "color-bg-layer-basement": "var(--mossy-color-palette-gray-200)",
  "color-bg-layer-default": "var(--mossy-color-palette-gray-00)",
  "color-bg-layer-default-pressed": "var(--mossy-color-palette-gray-100)",
  "color-bg-layer-fill": "var(--mossy-color-palette-gray-100)",
  "color-bg-layer-floating": "var(--mossy-color-palette-gray-00)",
  "color-bg-layer-floating-pressed": "var(--mossy-color-palette-gray-100)",
  "color-bg-magic-weak": "#f9f2ee",
  "color-bg-neutral-inverted": "var(--mossy-color-palette-gray-900)",
  "color-bg-neutral-inverted-pressed": "var(--mossy-color-palette-gray-800)",
  "color-bg-neutral-solid": "var(--mossy-color-palette-gray-1000)",
  "color-bg-neutral-solid-muted": "var(--mossy-color-palette-gray-800)",
  "color-bg-neutral-solid-muted-pressed": "var(--mossy-color-palette-gray-900)",
  "color-bg-neutral-weak": "var(--mossy-color-palette-gray-200)",
  "color-bg-neutral-weak-alpha": "var(--mossy-color-palette-static-black-alpha-200)",
  "color-bg-neutral-weak-alpha-pressed": "var(--mossy-color-palette-static-black-alpha-300)",
  "color-bg-neutral-weak-pressed": "var(--mossy-color-palette-gray-300)",
  "color-bg-overlay": "var(--mossy-color-palette-static-black-alpha-700)",
  "color-bg-overlay-muted": "var(--mossy-color-palette-static-black-alpha-500)",
  "color-bg-positive-solid": "var(--mossy-color-palette-green-700)",
  "color-bg-positive-solid-pressed": "var(--mossy-color-palette-green-800)",
  "color-bg-positive-weak": "var(--mossy-color-palette-green-100)",
  "color-bg-positive-weak-pressed": "var(--mossy-color-palette-green-200)",
  "color-bg-transparent": "#0000",
  "color-bg-transparent-pressed": "var(--mossy-color-palette-static-black-alpha-100)",
  "color-bg-warning-solid": "var(--mossy-color-palette-yellow-300)",
  "color-bg-warning-solid-pressed": "var(--mossy-color-palette-yellow-400)",
  "color-bg-warning-weak": "var(--mossy-color-palette-yellow-100)",
  "color-bg-warning-weak-pressed": "var(--mossy-color-palette-yellow-200)",
  "color-stroke-brand-solid": "var(--mossy-color-palette-mossy-700)",
  "color-stroke-brand-weak": "var(--mossy-color-palette-mossy-300)",
  "color-stroke-critical-solid": "var(--mossy-color-palette-red-700)",
  "color-stroke-critical-weak": "var(--mossy-color-palette-red-300)",
  "color-stroke-informative-solid": "var(--mossy-color-palette-blue-700)",
  "color-stroke-informative-weak": "var(--mossy-color-palette-blue-300)",
  "color-stroke-neutral-contrast": "var(--mossy-color-palette-gray-1000)",
  "color-stroke-neutral-muted": "var(--mossy-color-palette-static-black-alpha-300)",
  "color-stroke-neutral-solid": "var(--mossy-color-palette-gray-800)",
  "color-stroke-neutral-subtle": "var(--mossy-color-palette-static-black-alpha-200)",
  "color-stroke-neutral-weak": "var(--mossy-color-palette-gray-400)",
  "color-stroke-positive-solid": "var(--mossy-color-palette-green-700)",
  "color-stroke-positive-weak": "var(--mossy-color-palette-green-300)",
  "color-stroke-warning-solid": "var(--mossy-color-palette-yellow-700)",
  "color-stroke-warning-weak": "var(--mossy-color-palette-yellow-300)",
  "color-stroke-focus-ring": "var(--mossy-color-palette-blue-600)",
  "color-manner-temp-l1-bg": "#f1f2f3",
  "color-manner-temp-l1-text": "#757b85",
  "color-manner-temp-l10-bg": "#ffebee",
  "color-manner-temp-l10-text": "#cb0123",
  "color-manner-temp-l2-bg": "#f8f4ec",
  "color-manner-temp-l2-text": "#ab863f",
  "color-manner-temp-l3-bg": "#fff5e5",
  "color-manner-temp-l3-text": "#e08a00",
  "color-manner-temp-l4-bg": "#fff3e5",
  "color-manner-temp-l4-text": "#f57e00",
  "color-manner-temp-l5-bg": "#fff1e5",
  "color-manner-temp-l5-text": "#ff7300",
  "color-manner-temp-l6-bg": "#fff0e5",
  "color-manner-temp-l6-text": "#f60",
  "color-manner-temp-l7-bg": "#ffefe5",
  "color-manner-temp-l7-text": "#ff5100",
  "color-manner-temp-l8-bg": "#ffeee5",
  "color-manner-temp-l8-text": "#f30",
  "color-manner-temp-l9-bg": "#fdeded",
  "color-manner-temp-l9-text": "#e82c45",
  "color-banner-blue": "#e1f7ff",
  "color-banner-cool-gray": "#ebf1f5",
  "color-banner-green": "#f0fbe5",
  "color-banner-orange": "#fff2e1",
  "color-banner-pink": "#ffebf1",
  "color-banner-purple": "#f5ecff",
  "color-banner-red": "#ffecee",
  "color-banner-teal": "#e6faf6",
  "color-banner-warm-gray": "#f2f0ee",
  "color-banner-yellow": "#fffae1",
  "gradient-fade-layer-floating": "#fff0 0%, #000 100%",
  "gradient-fade-layer-default": "#000 0%, #fff0 100%",
  "gradient-glow-magic": "#fef6f7 0%, #fef0e7 80%, #f9f7f5 100%",
  "gradient-glow-magic-pressed": "#fbf0f2 0%, #ffe8db 80%, #f5f2ef 100%",
  "gradient-highlight-magic": "#f60 20%, #d25aca 100%",
  "gradient-highlight-magic-pressed": "#e14f00 20%, #ae58bf 100%",
  "gradient-shimmer-magic": "#fff9f500 0%, #fff9f5cc 46%, #fff9f5cc 54%, #fff9f500 100%",
  "gradient-shimmer-neutral": "#fff0 0%, #ffffffab 46%, #ffffffab 54%, #fff0 100%",
  "shadow-s1": "0px 1px 4px 0px #00000014",
  "shadow-s2": "0px 2px 10px 0px #0000001a",
  "shadow-s3": "0px 4px 16px 0px #0000001f"
} as const;

export const mossyDefaultDarkValues = {
  "color-palette-gray-00": "#000",
  "color-palette-gray-100": "#16171b",
  "color-palette-gray-200": "#1d2025",
  "color-palette-gray-300": "#2b2e35",
  "color-palette-gray-400": "#393d46",
  "color-palette-gray-500": "#5b606a",
  "color-palette-gray-600": "#868b94",
  "color-palette-gray-700": "#b0b3ba",
  "color-palette-gray-800": "#dcdee3",
  "color-palette-gray-900": "#e9eaec",
  "color-palette-gray-1000": "#f3f4f5",
  "color-palette-mossy-100": "#162219",
  "color-palette-mossy-200": "#1d3023",
  "color-palette-mossy-300": "#25402f",
  "color-palette-mossy-400": "#31553d",
  "color-palette-mossy-500": "#3d6a4c",
  "color-palette-mossy-600": "#4a7c59",
  "color-palette-mossy-700": "#68a074",
  "color-palette-mossy-800": "#8dbd95",
  "color-palette-mossy-900": "#b8d9be",
  "color-palette-mossy-1000": "#e6f2e9",
  "color-palette-blue-100": "#202742",
  "color-palette-blue-200": "#1e3352",
  "color-palette-blue-300": "#1a4275",
  "color-palette-blue-400": "#0f559e",
  "color-palette-blue-500": "#1964d8",
  "color-palette-blue-600": "#1e82eb",
  "color-palette-blue-700": "#41a2f9",
  "color-palette-blue-800": "#83bcf9",
  "color-palette-blue-900": "#b9d7fb",
  "color-palette-blue-1000": "#e5f0fe",
  "color-palette-red-100": "#322323",
  "color-palette-red-200": "#4f2624",
  "color-palette-red-300": "#742826",
  "color-palette-red-400": "#a12621",
  "color-palette-red-500": "#ca2319",
  "color-palette-red-600": "#f73526",
  "color-palette-red-700": "#ff6e60",
  "color-palette-red-800": "#ffa299",
  "color-palette-red-900": "#f8c5c3",
  "color-palette-red-1000": "#fdf2f2",
  "color-palette-green-100": "#202926",
  "color-palette-green-200": "#20362e",
  "color-palette-green-300": "#20493b",
  "color-palette-green-400": "#19604c",
  "color-palette-green-500": "#117956",
  "color-palette-green-600": "#1b946d",
  "color-palette-green-700": "#22b27f",
  "color-palette-green-800": "#35ce9a",
  "color-palette-green-900": "#93e5c0",
  "color-palette-green-1000": "#d4f6ef",
  "color-palette-yellow-100": "#302819",
  "color-palette-yellow-200": "#413218",
  "color-palette-yellow-300": "#543e15",
  "color-palette-yellow-400": "#714e15",
  "color-palette-yellow-500": "#91601b",
  "color-palette-yellow-600": "#b6720d",
  "color-palette-yellow-700": "#ca901c",
  "color-palette-yellow-800": "#dab156",
  "color-palette-yellow-900": "#e5d49b",
  "color-palette-yellow-1000": "#f7f0cd",
  "color-palette-purple-100": "#28213b",
  "color-palette-purple-200": "#3b2873",
  "color-palette-purple-300": "#443081",
  "color-palette-purple-400": "#5a3bb1",
  "color-palette-purple-500": "#764fd9",
  "color-palette-purple-600": "#8e6bee",
  "color-palette-purple-700": "#a78df0",
  "color-palette-purple-800": "#beadf2",
  "color-palette-purple-900": "#d9cefa",
  "color-palette-purple-1000": "#f0edfc",
  "color-palette-static-black": "#000",
  "color-palette-static-black-alpha-100": "#00000007",
  "color-palette-static-black-alpha-200": "#0000000c",
  "color-palette-static-black-alpha-300": "#00000010",
  "color-palette-static-black-alpha-400": "#00000021",
  "color-palette-static-black-alpha-500": "#0000002c",
  "color-palette-static-black-alpha-600": "#0000004c",
  "color-palette-static-black-alpha-700": "#00000074",
  "color-palette-static-black-alpha-800": "#000000a2",
  "color-palette-static-black-alpha-900": "#000000d0",
  "color-palette-static-black-alpha-1000": "#000000e3",
  "color-palette-static-white": "#fff",
  "color-palette-static-white-alpha-50": "#ffffff0d",
  "color-palette-static-white-alpha-100": "#ffffff17",
  "color-palette-static-white-alpha-200": "#ffffff20",
  "color-palette-static-white-alpha-300": "#ffffff2e",
  "color-palette-static-white-alpha-400": "#ffffff3d",
  "color-palette-static-white-alpha-500": "#ffffff60",
  "color-palette-static-white-alpha-600": "#ffffff8b",
  "color-palette-static-white-alpha-700": "#ffffffb3",
  "color-palette-static-white-alpha-800": "#ffffffde",
  "color-palette-static-white-alpha-900": "#ffffffea",
  "color-palette-static-white-alpha-1000": "#fffffff4",
  "color-fg-brand": "var(--mossy-color-palette-mossy-700)",
  "color-fg-brand-contrast": "var(--mossy-color-palette-mossy-700)",
  "color-fg-critical": "var(--mossy-color-palette-red-700)",
  "color-fg-critical-contrast": "var(--mossy-color-palette-red-900)",
  "color-fg-disabled": "var(--mossy-color-palette-gray-500)",
  "color-fg-informative": "var(--mossy-color-palette-blue-700)",
  "color-fg-informative-contrast": "var(--mossy-color-palette-blue-900)",
  "color-fg-neutral": "var(--mossy-color-palette-gray-1000)",
  "color-fg-neutral-inverted": "var(--mossy-color-palette-gray-100)",
  "color-fg-neutral-muted": "var(--mossy-color-palette-gray-800)",
  "color-fg-neutral-subtle": "var(--mossy-color-palette-gray-700)",
  "color-fg-placeholder": "var(--mossy-color-palette-gray-600)",
  "color-fg-positive": "var(--mossy-color-palette-green-700)",
  "color-fg-positive-contrast": "var(--mossy-color-palette-green-900)",
  "color-fg-warning": "var(--mossy-color-palette-yellow-700)",
  "color-fg-warning-contrast": "var(--mossy-color-palette-yellow-900)",
  "color-bg-brand-solid": "var(--mossy-color-palette-mossy-700)",
  "color-bg-brand-solid-pressed": "var(--mossy-color-palette-mossy-800)",
  "color-bg-brand-weak": "var(--mossy-color-palette-mossy-100)",
  "color-bg-brand-weak-pressed": "var(--mossy-color-palette-mossy-200)",
  "color-bg-critical-solid": "var(--mossy-color-palette-red-600)",
  "color-bg-critical-solid-pressed": "var(--mossy-color-palette-red-700)",
  "color-bg-critical-weak": "var(--mossy-color-palette-red-100)",
  "color-bg-critical-weak-pressed": "var(--mossy-color-palette-red-200)",
  "color-bg-disabled": "var(--mossy-color-palette-gray-300)",
  "color-bg-informative-solid": "var(--mossy-color-palette-blue-600)",
  "color-bg-informative-solid-pressed": "var(--mossy-color-palette-blue-700)",
  "color-bg-informative-weak": "var(--mossy-color-palette-blue-100)",
  "color-bg-informative-weak-pressed": "var(--mossy-color-palette-blue-200)",
  "color-bg-layer-basement": "var(--mossy-color-palette-gray-00)",
  "color-bg-layer-default": "var(--mossy-color-palette-gray-100)",
  "color-bg-layer-default-pressed": "var(--mossy-color-palette-gray-300)",
  "color-bg-layer-fill": "var(--mossy-color-palette-gray-200)",
  "color-bg-layer-floating": "var(--mossy-color-palette-gray-200)",
  "color-bg-layer-floating-pressed": "var(--mossy-color-palette-gray-300)",
  "color-bg-magic-weak": "#201f1f",
  "color-bg-neutral-inverted": "var(--mossy-color-palette-gray-1000)",
  "color-bg-neutral-inverted-pressed": "var(--mossy-color-palette-gray-800)",
  "color-bg-neutral-solid": "var(--mossy-color-palette-gray-300)",
  "color-bg-neutral-solid-muted": "var(--mossy-color-palette-gray-400)",
  "color-bg-neutral-solid-muted-pressed": "var(--mossy-color-palette-gray-500)",
  "color-bg-neutral-weak": "var(--mossy-color-palette-gray-300)",
  "color-bg-neutral-weak-alpha": "var(--mossy-color-palette-static-white-alpha-200)",
  "color-bg-neutral-weak-alpha-pressed": "var(--mossy-color-palette-static-white-alpha-300)",
  "color-bg-neutral-weak-pressed": "var(--mossy-color-palette-gray-400)",
  "color-bg-overlay": "var(--mossy-color-palette-static-black-alpha-700)",
  "color-bg-overlay-muted": "var(--mossy-color-palette-static-black-alpha-500)",
  "color-bg-positive-solid": "var(--mossy-color-palette-green-500)",
  "color-bg-positive-solid-pressed": "var(--mossy-color-palette-green-600)",
  "color-bg-positive-weak": "var(--mossy-color-palette-green-100)",
  "color-bg-positive-weak-pressed": "var(--mossy-color-palette-green-200)",
  "color-bg-transparent": "#fff0",
  "color-bg-transparent-pressed": "var(--mossy-color-palette-static-white-alpha-50)",
  "color-bg-warning-solid": "var(--mossy-color-palette-yellow-800)",
  "color-bg-warning-solid-pressed": "var(--mossy-color-palette-yellow-900)",
  "color-bg-warning-weak": "var(--mossy-color-palette-yellow-100)",
  "color-bg-warning-weak-pressed": "var(--mossy-color-palette-yellow-200)",
  "color-stroke-brand-solid": "var(--mossy-color-palette-mossy-700)",
  "color-stroke-brand-weak": "var(--mossy-color-palette-mossy-300)",
  "color-stroke-critical-solid": "var(--mossy-color-palette-red-700)",
  "color-stroke-critical-weak": "var(--mossy-color-palette-red-300)",
  "color-stroke-informative-solid": "var(--mossy-color-palette-blue-700)",
  "color-stroke-informative-weak": "var(--mossy-color-palette-blue-300)",
  "color-stroke-neutral-contrast": "var(--mossy-color-palette-gray-1000)",
  "color-stroke-neutral-muted": "var(--mossy-color-palette-static-white-alpha-100)",
  "color-stroke-neutral-solid": "var(--mossy-color-palette-gray-800)",
  "color-stroke-neutral-subtle": "var(--mossy-color-palette-static-white-alpha-50)",
  "color-stroke-neutral-weak": "var(--mossy-color-palette-gray-400)",
  "color-stroke-positive-solid": "var(--mossy-color-palette-green-700)",
  "color-stroke-positive-weak": "var(--mossy-color-palette-green-300)",
  "color-stroke-warning-solid": "var(--mossy-color-palette-yellow-700)",
  "color-stroke-warning-weak": "var(--mossy-color-palette-yellow-300)",
  "color-stroke-focus-ring": "var(--mossy-color-palette-blue-600)",
  "color-manner-temp-l1-bg": "#292929",
  "color-manner-temp-l1-text": "#b8b8b9",
  "color-manner-temp-l10-bg": "#34040a",
  "color-manner-temp-l10-text": "#fb6f82",
  "color-manner-temp-l2-bg": "#332605",
  "color-manner-temp-l2-text": "#f5db97",
  "color-manner-temp-l3-bg": "#372b01",
  "color-manner-temp-l3-text": "#fdda65",
  "color-manner-temp-l4-bg": "#372301",
  "color-manner-temp-l4-text": "#fbbe55",
  "color-manner-temp-l5-bg": "#371f01",
  "color-manner-temp-l5-text": "#faac4b",
  "color-manner-temp-l6-bg": "#351b03",
  "color-manner-temp-l6-text": "#fc9855",
  "color-manner-temp-l7-bg": "#371701",
  "color-manner-temp-l7-text": "#f97a25",
  "color-manner-temp-l8-bg": "#380f00",
  "color-manner-temp-l8-text": "#fe6a34",
  "color-manner-temp-l9-bg": "#380500",
  "color-manner-temp-l9-text": "#fe6a5d",
  "color-banner-blue": "#0d2a3a",
  "color-banner-cool-gray": "#242c33",
  "color-banner-green": "#1e361c",
  "color-banner-orange": "#42230a",
  "color-banner-pink": "#3b172c",
  "color-banner-purple": "#2e1e45",
  "color-banner-red": "#3a0f15",
  "color-banner-teal": "#143633",
  "color-banner-warm-gray": "#2f2b27",
  "color-banner-yellow": "#3e2b00",
  "gradient-fade-layer-floating": "#1d202500 0%, #000 100%",
  "gradient-fade-layer-default": "#000 0%, #16171b00 100%",
  "gradient-glow-magic": "#2d252d 0%, #3a312b 80%, #333232 100%",
  "gradient-glow-magic-pressed": "#3e333e 0%, #51453e 80%, #434242 100%",
  "gradient-highlight-magic": "#f60 20%, #d25aca 100%",
  "gradient-highlight-magic-pressed": "#ff9e65 20%, #e89bee 100%",
  "gradient-shimmer-magic": "#fff9f500 0%, #fff9f51a 46%, #fff9f51a 54%, #fff9f500 100%",
  "gradient-shimmer-neutral": "#fff0 0%, #ffffff1a 46%, #ffffff1a 54%, #fff0 100%",
  "shadow-s1": "0px 1px 4px 0px #00000080",
  "shadow-s2": "0px 2px 10px 0px #000000ad",
  "shadow-s3": "0px 4px 16px 0px #000c"
} as const;

export const mossyDefaultTextStyleDefinitions = {
  "textStyleScreenTitle": {
    "fontSize": "var(--mossy-font-size-t10)",
    "lineHeight": "var(--mossy-line-height-t10)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleArticleBody": {
    "fontSize": "var(--mossy-font-size-t5)",
    "lineHeight": "var(--mossy-line-height-t6)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleArticleNote": {
    "fontSize": "var(--mossy-font-size-t4)",
    "lineHeight": "var(--mossy-line-height-t5)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT1Regular": {
    "fontSize": "var(--mossy-font-size-t1)",
    "lineHeight": "var(--mossy-line-height-t1)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT1Medium": {
    "fontSize": "var(--mossy-font-size-t1)",
    "lineHeight": "var(--mossy-line-height-t1)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT1Bold": {
    "fontSize": "var(--mossy-font-size-t1)",
    "lineHeight": "var(--mossy-line-height-t1)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT2Regular": {
    "fontSize": "var(--mossy-font-size-t2)",
    "lineHeight": "var(--mossy-line-height-t2)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT2Medium": {
    "fontSize": "var(--mossy-font-size-t2)",
    "lineHeight": "var(--mossy-line-height-t2)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT2Bold": {
    "fontSize": "var(--mossy-font-size-t2)",
    "lineHeight": "var(--mossy-line-height-t2)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT3Regular": {
    "fontSize": "var(--mossy-font-size-t3)",
    "lineHeight": "var(--mossy-line-height-t3)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT3Medium": {
    "fontSize": "var(--mossy-font-size-t3)",
    "lineHeight": "var(--mossy-line-height-t3)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT3Bold": {
    "fontSize": "var(--mossy-font-size-t3)",
    "lineHeight": "var(--mossy-line-height-t3)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT4Regular": {
    "fontSize": "var(--mossy-font-size-t4)",
    "lineHeight": "var(--mossy-line-height-t4)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT4Medium": {
    "fontSize": "var(--mossy-font-size-t4)",
    "lineHeight": "var(--mossy-line-height-t4)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT4Bold": {
    "fontSize": "var(--mossy-font-size-t4)",
    "lineHeight": "var(--mossy-line-height-t4)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT5Regular": {
    "fontSize": "var(--mossy-font-size-t5)",
    "lineHeight": "var(--mossy-line-height-t5)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT5Medium": {
    "fontSize": "var(--mossy-font-size-t5)",
    "lineHeight": "var(--mossy-line-height-t5)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT5Bold": {
    "fontSize": "var(--mossy-font-size-t5)",
    "lineHeight": "var(--mossy-line-height-t5)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT6Regular": {
    "fontSize": "var(--mossy-font-size-t6)",
    "lineHeight": "var(--mossy-line-height-t6)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT6Medium": {
    "fontSize": "var(--mossy-font-size-t6)",
    "lineHeight": "var(--mossy-line-height-t6)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT6Bold": {
    "fontSize": "var(--mossy-font-size-t6)",
    "lineHeight": "var(--mossy-line-height-t6)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT7Regular": {
    "fontSize": "var(--mossy-font-size-t7)",
    "lineHeight": "var(--mossy-line-height-t7)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT7Medium": {
    "fontSize": "var(--mossy-font-size-t7)",
    "lineHeight": "var(--mossy-line-height-t7)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT7Bold": {
    "fontSize": "var(--mossy-font-size-t7)",
    "lineHeight": "var(--mossy-line-height-t7)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT8Bold": {
    "fontSize": "var(--mossy-font-size-t8)",
    "lineHeight": "var(--mossy-line-height-t8)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT9Bold": {
    "fontSize": "var(--mossy-font-size-t9)",
    "lineHeight": "var(--mossy-line-height-t9)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT10Bold": {
    "fontSize": "var(--mossy-font-size-t10)",
    "lineHeight": "var(--mossy-line-height-t10)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT1StaticRegular": {
    "fontSize": "var(--mossy-font-size-t1-static)",
    "lineHeight": "var(--mossy-line-height-t1-static)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT1StaticMedium": {
    "fontSize": "var(--mossy-font-size-t1-static)",
    "lineHeight": "var(--mossy-line-height-t1-static)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT1StaticBold": {
    "fontSize": "var(--mossy-font-size-t1-static)",
    "lineHeight": "var(--mossy-line-height-t1-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT2StaticRegular": {
    "fontSize": "var(--mossy-font-size-t2-static)",
    "lineHeight": "var(--mossy-line-height-t2-static)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT2StaticMedium": {
    "fontSize": "var(--mossy-font-size-t2-static)",
    "lineHeight": "var(--mossy-line-height-t2-static)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT2StaticBold": {
    "fontSize": "var(--mossy-font-size-t2-static)",
    "lineHeight": "var(--mossy-line-height-t2-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT3StaticRegular": {
    "fontSize": "var(--mossy-font-size-t3-static)",
    "lineHeight": "var(--mossy-line-height-t3-static)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT3StaticMedium": {
    "fontSize": "var(--mossy-font-size-t3-static)",
    "lineHeight": "var(--mossy-line-height-t3-static)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT3StaticBold": {
    "fontSize": "var(--mossy-font-size-t3-static)",
    "lineHeight": "var(--mossy-line-height-t3-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT4StaticRegular": {
    "fontSize": "var(--mossy-font-size-t4-static)",
    "lineHeight": "var(--mossy-line-height-t4-static)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT4StaticMedium": {
    "fontSize": "var(--mossy-font-size-t4-static)",
    "lineHeight": "var(--mossy-line-height-t4-static)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT4StaticBold": {
    "fontSize": "var(--mossy-font-size-t4-static)",
    "lineHeight": "var(--mossy-line-height-t4-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT5StaticRegular": {
    "fontSize": "var(--mossy-font-size-t5-static)",
    "lineHeight": "var(--mossy-line-height-t5-static)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT5StaticMedium": {
    "fontSize": "var(--mossy-font-size-t5-static)",
    "lineHeight": "var(--mossy-line-height-t5-static)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT5StaticBold": {
    "fontSize": "var(--mossy-font-size-t5-static)",
    "lineHeight": "var(--mossy-line-height-t5-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT6StaticRegular": {
    "fontSize": "var(--mossy-font-size-t6-static)",
    "lineHeight": "var(--mossy-line-height-t6-static)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT6StaticMedium": {
    "fontSize": "var(--mossy-font-size-t6-static)",
    "lineHeight": "var(--mossy-line-height-t6-static)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT6StaticBold": {
    "fontSize": "var(--mossy-font-size-t6-static)",
    "lineHeight": "var(--mossy-line-height-t6-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT7StaticRegular": {
    "fontSize": "var(--mossy-font-size-t7-static)",
    "lineHeight": "var(--mossy-line-height-t7-static)",
    "fontWeight": "var(--mossy-font-weight-regular)"
  },
  "textStyleT7StaticMedium": {
    "fontSize": "var(--mossy-font-size-t7-static)",
    "lineHeight": "var(--mossy-line-height-t7-static)",
    "fontWeight": "var(--mossy-font-weight-medium)"
  },
  "textStyleT7StaticBold": {
    "fontSize": "var(--mossy-font-size-t7-static)",
    "lineHeight": "var(--mossy-line-height-t7-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT8StaticBold": {
    "fontSize": "var(--mossy-font-size-t8-static)",
    "lineHeight": "var(--mossy-line-height-t8-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT9StaticBold": {
    "fontSize": "var(--mossy-font-size-t9-static)",
    "lineHeight": "var(--mossy-line-height-t9-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  },
  "textStyleT10StaticBold": {
    "fontSize": "var(--mossy-font-size-t10-static)",
    "lineHeight": "var(--mossy-line-height-t10-static)",
    "fontWeight": "var(--mossy-font-weight-bold)"
  }
} as const;

export type MossyTextStyleName = keyof typeof mossyDefaultTextStyleDefinitions;
