import type { ShowcaseComponent } from './types';

export const segmentedOptions = ['추천', '인기', '최신'];

export const showcaseComponents: ShowcaseComponent[] = [
  { name: 'Accordion', slug: 'accordion', group: 'Components' },
  { name: 'Alert', slug: 'alert', group: 'Components' },
  { name: 'Alert Dialog', slug: 'alert-dialog', group: 'Components' },
  { name: 'Aspect Ratio', slug: 'aspect-ratio', group: 'Components' },
  { name: 'Avatar', slug: 'avatar', group: 'Components' },
  { name: 'Badge', slug: 'badge', group: 'Components' },
  { name: 'Box', slug: 'box', group: 'Layout', preview: 'box' },
  { name: 'Button', slug: 'button', group: 'Components' },
  { name: 'Card', slug: 'card', group: 'Components' },
  { name: 'Checkbox', slug: 'checkbox', group: 'Controls', preview: 'checkbox' },
  { name: 'Collapsible', slug: 'collapsible', group: 'Components' },
  { name: 'Context Menu', slug: 'context-menu', group: 'Components' },
  { name: 'Dialog', slug: 'dialog', group: 'Components' },
  { name: 'Divider', slug: 'divider', group: 'Layout', preview: 'divider' },
  { name: 'Dropdown Menu', slug: 'dropdown-menu', group: 'Components' },
  { name: 'Flex', slug: 'flex', group: 'Layout', preview: 'flex' },
  { name: 'Float', slug: 'float', group: 'Layout', preview: 'float' },
  { name: 'Grid', slug: 'grid', group: 'Layout', preview: 'grid' },
  { name: 'Hover Card', slug: 'hover-card', group: 'Components' },
  { name: 'HStack', slug: 'hstack', group: 'Layout', preview: 'hstack' },
  { name: 'Input', slug: 'input', group: 'Components' },
  { name: 'Label', slug: 'label', group: 'Components' },
  { name: 'List', slug: 'list', group: 'Components', preview: 'list' },
  { name: 'ListHeader', slug: 'list-header', group: 'Components', preview: 'list' },
  {
    name: 'Loading Indicator',
    slug: 'loading-indicator',
    group: 'Feedback',
    preview: 'loading-indicator',
  },
  { name: 'Menubar', slug: 'menubar', group: 'Components' },
  { name: 'Popover', slug: 'popover', group: 'Components' },
  {
    name: 'Progress Circle',
    slug: 'progress-circle',
    group: 'Feedback',
    preview: 'progress-circle',
  },
  { name: 'Radio Group', slug: 'radio-group', group: 'Components' },
  { name: 'ScrollFog', slug: 'scroll-fog', group: 'Layout', preview: 'scroll-fog' },
  { name: 'ScrollView', slug: 'scroll-view', group: 'Layout', preview: 'scroll-view' },
  {
    name: 'Segmented Control',
    slug: 'segmented-control',
    group: 'Controls',
    preview: 'segmented-control',
  },
  { name: 'Select', slug: 'select', group: 'Components' },
  { name: 'Separator', slug: 'separator', group: 'Components' },
  { name: 'Skeleton', slug: 'skeleton', group: 'Components' },
  { name: 'Slider', slug: 'slider', group: 'Controls', preview: 'slider' },
  { name: 'Spacer', slug: 'spacer', group: 'Layout', preview: 'spacer' },
  { name: 'Switch', slug: 'switch', group: 'Controls', preview: 'switch' },
  { name: 'Tabs', slug: 'tabs', group: 'Components' },
  { name: 'Text', slug: 'text', group: 'Typography', preview: 'text' },
  { name: 'Textarea', slug: 'textarea', group: 'Components' },
  { name: 'Toggle', slug: 'toggle', group: 'Components' },
  { name: 'Toggle Group', slug: 'toggle-group', group: 'Components' },
  { name: 'Tooltip', slug: 'tooltip', group: 'Components' },
  { name: 'VStack', slug: 'vstack', group: 'Layout', preview: 'vstack' },
];
