import type { ShowcaseComponent } from './types';

export const segmentedOptions = ['추천', '인기', '최신'];

export const showcaseComponents: ShowcaseComponent[] = [
  { name: 'ActionButton', slug: 'action-button', group: '미구현' },
  { name: 'ActionChip', slug: 'action-chip', group: '미구현' },
  { name: 'ActionSheet', slug: 'action-sheet', group: '제약' },
  { name: 'Article', slug: 'article', group: '미구현' },
  { name: 'AspectRatio', slug: 'aspect-ratio', group: '미구현' },
  { name: 'Avatar', slug: 'avatar', group: '미구현' },
  { name: 'Badge', slug: 'badge', group: '미구현' },
  { name: 'BottomSheet', slug: 'bottom-sheet', group: '제약' },
  { name: 'BottomSheetHandle', slug: 'bottom-sheet-handle', group: '제약' },
  { name: 'Box', slug: 'box', group: '부분완료', preview: 'box' },
  { name: 'Callout', slug: 'callout', group: '미구현' },
  { name: 'Celsius', slug: 'celsius', group: '미구현' },
  { name: 'Checkbox', slug: 'checkbox', group: '부분완료', preview: 'checkbox' },
  { name: 'Chip', slug: 'chip', group: '미구현' },
  { name: 'ChipTabs', slug: 'chip-tabs', group: '미구현' },
  { name: 'Columns', slug: 'columns', group: '미구현' },
  { name: 'ConsistentWidth', slug: 'consistent-width', group: '제약' },
  { name: 'ContentPlaceholder', slug: 'content-placeholder', group: '미구현' },
  {
    name: 'ContextualFloatingButton',
    slug: 'contextual-floating-button',
    group: '미구현',
  },
  { name: 'ControlChip', slug: 'control-chip', group: '미구현' },
  { name: 'Count', slug: 'count', group: '미구현' },
  { name: 'Dialog', slug: 'dialog', group: '제약' },
  { name: 'Divider', slug: 'divider', group: '부분완료', preview: 'divider' },
  { name: 'ExtendedActionSheet', slug: 'extended-action-sheet', group: '제약' },
  { name: 'ExtendedFab', slug: 'extended-fab', group: '미구현' },
  { name: 'Fab', slug: 'fab', group: '미구현' },
  { name: 'Field', slug: 'field', group: '미구현' },
  { name: 'FieldButton', slug: 'field-button', group: '미구현' },
  { name: 'Fieldset', slug: 'fieldset', group: '미구현' },
  { name: 'Flex', slug: 'flex', group: '부분완료', preview: 'flex' },
  { name: 'Float', slug: 'float', group: '부분완료', preview: 'float' },
  {
    name: 'FloatingActionButton',
    slug: 'floating-action-button',
    group: '미구현',
  },
  { name: 'Grid', slug: 'grid', group: '부분완료', preview: 'grid' },
  { name: 'GridItem', slug: 'grid-item', group: '미구현' },
  { name: 'HelpBubble', slug: 'help-bubble', group: '제약' },
  { name: 'Icon', slug: 'icon', group: '부분완료' },
  { name: 'IdentityPlaceholder', slug: 'identity-placeholder', group: '미구현' },
  { name: 'ImageFrame', slug: 'image-frame', group: '제약' },
  { name: 'Inline', slug: 'inline', group: '미구현' },
  { name: 'InlineBanner', slug: 'inline-banner', group: '미구현' },
  { name: 'LinkContent', slug: 'link-content', group: '미구현' },
  { name: 'List', slug: 'list', group: '부분완료', preview: 'list' },
  {
    name: 'LoadingIndicator',
    slug: 'loading-indicator',
    group: '부분완료',
    preview: 'loading-indicator',
  },
  { name: 'MannerTemp', slug: 'manner-temp', group: '미구현' },
  { name: 'MannerTempBadge', slug: 'manner-temp-badge', group: '미구현' },
  { name: 'MenuSheet', slug: 'menu-sheet', group: '제약' },
  { name: 'NotificationBadge', slug: 'notification-badge', group: '미구현' },
  { name: 'PageBanner', slug: 'page-banner', group: '미구현' },
  { name: 'Portal', slug: 'portal', group: '제약' },
  {
    name: 'ProgressCircle',
    slug: 'progress-circle',
    group: '부분완료',
    preview: 'progress-circle',
  },
  { name: 'PullToRefresh', slug: 'pull-to-refresh', group: '미구현' },
  { name: 'RadioGroup', slug: 'radio-group', group: '미구현' },
  { name: 'RadioGroupField', slug: 'radio-group-field', group: '미구현' },
  { name: 'ReactionButton', slug: 'reaction-button', group: '미구현' },
  { name: 'ResponsivePair', slug: 'responsive-pair', group: '미구현' },
  { name: 'ScrollFog', slug: 'scroll-fog', group: '부분완료', preview: 'scroll-fog' },
  {
    name: 'SegmentedControl',
    slug: 'segmented-control',
    group: '부분완료',
    preview: 'segmented-control',
  },
  { name: 'SelectBox', slug: 'select-box', group: '미구현' },
  { name: 'Skeleton', slug: 'skeleton', group: '미구현' },
  { name: 'Slider', slug: 'slider', group: '부분완료', preview: 'slider' },
  { name: 'Snackbar', slug: 'snackbar', group: '제약' },
  { name: 'Stack', slug: 'stack', group: '부분완료', preview: 'vstack' },
  { name: 'Switch', slug: 'switch', group: '부분완료', preview: 'switch' },
  { name: 'Tabs', slug: 'tabs', group: '미구현' },
  { name: 'TagGroup', slug: 'tag-group', group: '미구현' },
  { name: 'Text', slug: 'text', group: '부분완료', preview: 'text' },
  { name: 'TextField', slug: 'text-field', group: '부분완료', preview: 'text-field' },
  { name: 'ToggleButton', slug: 'toggle-button', group: '미구현' },
  { name: 'VisuallyHidden', slug: 'visually-hidden', group: '제약' },
];
